/* Automatically generated by './build/bin/build-entry.js' */

import MessageBox from '../packages/message-box/index.js';
import Tree from '../packages/tree/index.js';
import Notification from '../packages/notification/index.js';
import Loading from '../packages/loading/index.js';
import Message from '../packages/message/index.js';
import InfiniteScroll from '../packages/infinite-scroll/index.js';
import MessageBoxCenter from '../packages/message-box-center/index.js';
import locale from 'element-ui/src/locale';

const components = [
  Tree
];

const install = (Vue, opts = {}) => {
  locale.use(opts.locale);
  locale.i18n(opts.i18n);

  components.forEach(component => {
    Vue.component(component.name, component);
  });

  Vue.use(InfiniteScroll);
  Vue.use(Loading.directive);

  Vue.prototype.$ELEMENT = {
    size: opts.size || '',
    zIndex: opts.zIndex || 2000
  };

  Vue.prototype.$loading = Loading.service;
  Vue.prototype.$msgbox = MessageBox;
  Vue.prototype.$alert = MessageBox.alert;
  Vue.prototype.$confirm = MessageBox.confirm;
  Vue.prototype.$prompt = MessageBox.prompt;
  Vue.prototype.$notify = Notification;
  Vue.prototype.$message = Message;
  Vue.prototype.$alertCenter = MessageBoxCenter.alert;
  Vue.prototype.$confirmCenter = MessageBoxCenter.confirm;
};

/* istanbul ignore if */
if (typeof window !== 'undefined' && window.Vue) {
  install(window.Vue);
}

export default {
  version: '2.12.0',
  install,
  Tree
};
