/* Automatically generated by './build/bin/build-entry.js' */
import Tree from '../packages/tree/index.js';
import CollapseTransition from 'element-ui/src/transitions/collapse-transition';

const components = [
  Tree,
  Image,
  CollapseTransition
];

const install = function (Vue, opts = {}) {

  components.forEach(component => {
    Vue.component(component.name, component);
  });

  Vue.prototype.$ELEMENT = {
    size: opts.size || '',
    zIndex: opts.zIndex || 2000
  };

  Vue.prototype.$notify = Notification;

};

/* istanbul ignore if */
if (typeof window !== 'undefined' && window.Vue) {
  install(window.Vue);
}

export default {
  version: '2.12.0',
  install,
  CollapseTransition,
  Tree
};
